export default [
  {
    small: '`',
    shift: '~',
    code: 'Backquote',
    size: 'common',
  },
  {
    small: '1',
    shift: '!',
    code: 'Digit1',
    size: 'common',
  },
  {
    small: '2',
    shift: '@',
    code: 'Digit2',
    size: 'common',
  },
  {
    small: '3',
    shift: '#',
    code: 'Digit3',
    size: 'common',
  },
  {
    small: '4',
    shift: '$',
    code: 'Digit4',
    size: 'common',
  },
  {
    small: '5',
    shift: '%',
    code: 'Digit5',
    size: 'common',
  },
  {
    small: '6',
    shift: '^',
    code: 'Digit6',
    size: 'common',
  },
  {
    small: '7',
    shift: '&',
    code: 'Digit7',
    size: 'common',
  },
  {
    small: '8',
    shift: '*',
    code: 'Digit8',
    size: 'common',
  },
  {
    small: '9',
    shift: '(',
    code: 'Digit9',
    size: 'common',
  },
  {
    small: '0',
    shift: ')',
    code: 'Digit0',
    size: 'common',
  },
  {
    small: '-',
    shift: '_',
    code: 'NumpadSubtract',
    size: 'common',
  },
  {
    small: '=',
    shift: '+',
    code: 'Equal',
    size: 'common',
  },
  {
    small: 'Backspace',
    shift: 'Backspace',
    code: 'Backspace',
    size: 'double',
  },
  {
    small: 'Tab',
    shift: 'Tab',
    code: 'Tab',
    size: 'double',
  },
  {
    small: 'q',
    shift: 'Q',
    code: 'KeyQ',
    size: 'common',
  },
  {
    small: 'w',
    shift: 'W',
    code: 'KeyW',
    size: 'common',
  },
  {
    small: 'e',
    shift: 'E',
    code: 'KeyE',
    size: 'common',
  },
  {
    small: 'r',
    shift: 'R',
    code: 'KeyR',
    size: 'common',
  },
  {
    small: 't',
    shift: 'T',
    code: 'KeyT',
    size: 'common',
  },
  {
    small: 'y',
    shift: 'Y',
    code: 'KeyY',
    size: 'common',
  },
  {
    small: 'u',
    shift: 'U',
    code: 'KeyU',
    size: 'common',
  },
  {
    small: 'i',
    shift: 'I',
    code: 'KeyI',
    size: 'common',
  },
  {
    small: 'o',
    shift: 'O',
    code: 'KeyO',
    size: 'common',
  },
  {
    small: 'p',
    shift: 'P',
    code: 'KeyP',
    size: 'common',
  },
  {
    small: '[',
    shift: '{',
    code: 'BracketLeft',
    size: 'common',
  },
  {
    small: ']',
    shift: '}',
    code: 'BracketRight',
    size: 'common',
  },
  {
    small: '\\',
    shift: '|',
    code: 'Backslash',
    size: 'common',
  },
  {
    small: 'Delete',
    shift: 'Delete',
    code: 'Delete',
    size: 'common',
  },
  {
    small: 'CapsLock',
    shift: 'CapsLock',
    code: 'CapsLock',
    size: 'double',
  },
  {
    small: 'a',
    shift: 'A',
    code: 'KeyA',
    size: 'common',
  },
  {
    small: 's',
    shift: 'S',
    code: 'KeyS',
    size: 'common',
  },
  {
    small: 'd',
    shift: 'D',
    code: 'KeyD',
    size: 'common',
  },
  {
    small: 'f',
    shift: 'F',
    code: 'KeyF',
    size: 'common',
  },
  {
    small: 'g',
    shift: 'G',
    code: 'KeyG',
    size: 'common',
  },
  {
    small: 'h',
    shift: 'H',
    code: 'KeyH',
    size: 'common',
  },
  {
    small: 'j',
    shift: 'J',
    code: 'KeyJ',
    size: 'common',
  },
  {
    small: 'k',
    shift: 'K',
    code: 'KeyK',
    size: 'common',
  },
  {
    small: 'l',
    shift: 'L',
    code: 'KeyL',
    size: 'common',
  },
  {
    small: ';',
    shift: ':',
    code: 'Semicolon',
    size: 'common',
  },
  {
    small: "'",
    shift: '"',
    code: 'Quote',
    size: 'common',
  },
  {
    small: 'Enter',
    shift: 'Enter',
    code: 'Enter',
    size: 'double',
  },
  {
    small: 'Shift',
    shift: 'Shift',
    code: 'ShiftLeft',
    size: 'double',
  },
  {
    small: 'z',
    shift: 'Z',
    code: 'KeyZ',
    size: 'common',
  },
  {
    small: 'x',
    shift: 'X',
    code: 'KeyX',
    size: 'common',
  },
  {
    small: 'c',
    shift: 'C',
    code: 'KeyC',
    size: 'common',
  },
  {
    small: 'v',
    shift: 'V',
    code: 'KeyV',
    size: 'common',
  },
  {
    small: 'b',
    shift: 'B',
    code: 'KeyB',
    size: 'common',
  },
  {
    small: 'n',
    shift: 'N',
    code: 'KeyN',
    size: 'common',
  },
  {
    small: 'm',
    shift: 'M',
    code: 'KeyM',
    size: 'common',
  },
  {
    small: ',',
    shift: '<',
    code: 'Comma',
    size: 'common',
  },
  {
    small: '.',
    shift: '>',
    code: 'Period',
    size: 'common',
  },
  {
    small: '/',
    shift: '?',
    code: 'Slash',
    size: 'common',
  },
  {
    small: '&uarr;',
    shift: '&uarr;',
    code: 'ArrowUp',
    size: 'common',
  },
  {
    small: 'Shift',
    shift: 'Shift',
    code: 'ShiftRight',
    size: 'double',
  },
  {
    small: 'Ctrl',
    shift: 'Ctrl',
    code: 'ControlLeft',
    size: 'common',
  },
  {
    small: 'Win',
    shift: 'Win',
    code: 'MetaLeft',
    size: 'common',
  },
  {
    small: 'Alt',
    shift: 'Alt',
    code: 'AltLeft',
    size: 'common',
  },
  {
    small: 'Space',
    shift: 'Space',
    code: 'Space',
    size: 'space_button',
  },
  {
    small: 'Alt',
    shift: 'Alt',
    code: 'AltRight',
    size: 'common',
  },
  {
    small: '&larr;',
    shift: '&larr;',
    code: 'ArrowLeft',
    size: 'common',
  },
  {
    small: '&darr;',
    shift: '&darr;',
    code: 'ArrowDown',
    size: 'common',
  },
  {
    small: '&rarr;',
    shift: '&rarr;',
    code: 'ArrowRight',
    size: 'common',
  },
  {
    small: 'Ctrl',
    shift: 'Ctrl',
    code: 'ControlRight',
    size: 'common',
  },
];
