export default [
  {
    small: 'ё',
    shift: 'Ё',
    code: 'Backquote',
    size: 'common',
  },
  {
    small: '1',
    shift: '!',
    code: 'Digit1',
    size: 'common',
  },
  {
    small: '2',
    shift: '"',
    code: 'Digit2',
    size: 'common',
  },
  {
    small: '3',
    shift: '№',
    code: 'Digit3',
    size: 'common',
  },
  {
    small: '4',
    shift: ';',
    code: 'Digit4',
    size: 'common',
  },
  {
    small: '5',
    shift: '%',
    code: 'Digit5',
    size: 'common',
  },
  {
    small: '6',
    shift: ':',
    code: 'Digit6',
    size: 'common',
  },
  {
    small: '7',
    shift: '?',
    code: 'Digit7',
    size: 'common',
  },
  {
    small: '8',
    shift: '*',
    code: 'Digit8',
    size: 'common',
  },
  {
    small: '9',
    shift: '(',
    code: 'Digit9',
    size: 'common',
  },
  {
    small: '0',
    shift: ')',
    code: 'Digit0',
    size: 'common',
  },
  {
    small: '-',
    shift: '_',
    code: 'NumpadSubtract',
    size: 'common',
  },
  {
    small: '=',
    shift: '+',
    code: 'Equal',
    size: 'common',
  },
  {
    small: 'Backspace',
    shift: 'Backspace',
    code: 'Backspace',
    size: 'double',
  },
  {
    small: 'Tab',
    shift: 'Tab',
    code: 'Tab',
    size: 'double',
  },
  {
    small: 'й',
    shift: 'Й',
    code: 'KeyQ',
    size: 'common',
  },
  {
    small: 'ц',
    shift: 'Ц',
    code: 'KeyW',
    size: 'common',
  },
  {
    small: 'у',
    shift: 'У',
    code: 'KeyE',
    size: 'common',
  },
  {
    small: 'к',
    shift: 'К',
    code: 'KeyR',
    size: 'common',
  },
  {
    small: 'е',
    shift: 'Е',
    code: 'KeyT',
    size: 'common',
  },
  {
    small: 'н',
    shift: 'Н',
    code: 'KeyY',
    size: 'common',
  },
  {
    small: 'г',
    shift: 'Г',
    code: 'KeyU',
    size: 'common',
  },
  {
    small: 'ш',
    shift: 'Ш',
    code: 'KeyI',
    size: 'common',
  },
  {
    small: 'щ',
    shift: 'Щ',
    code: 'KeyO',
    size: 'common',
  },
  {
    small: 'з',
    shift: 'З',
    code: 'KeyP',
    size: 'common',
  },
  {
    small: 'х',
    shift: 'Х',
    code: 'BracketLeft',
    size: 'common',
  },
  {
    small: 'ъ',
    shift: 'Ъ',
    code: 'BracketRight',
    size: 'common',
  },
  {
    small: '\\',
    shift: '/',
    code: 'Backslash',
    size: 'common',
  },
  {
    small: 'Delete',
    shift: 'Delete',
    code: 'Delete',
    size: 'common',
  },
  {
    small: 'CapsLock',
    shift: 'CapsLock',
    code: 'CapsLock',
    size: 'double',
  },
  {
    small: 'ф',
    shift: 'Ф',
    code: 'KeyA',
    size: 'common',
  },
  {
    small: 'ы',
    shift: 'Ы',
    code: 'KeyS',
    size: 'common',
  },
  {
    small: 'в',
    shift: 'В',
    code: 'KeyD',
    size: 'common',
  },
  {
    small: 'а',
    shift: 'А',
    code: 'KeyF',
    size: 'common',
  },
  {
    small: 'п',
    shift: 'П',
    code: 'KeyG',
    size: 'common',
  },
  {
    small: 'р',
    shift: 'Р',
    code: 'KeyH',
    size: 'common',
  },
  {
    small: 'о',
    shift: 'О',
    code: 'KeyJ',
    size: 'common',
  },
  {
    small: 'л',
    shift: 'Л',
    code: 'KeyK',
    size: 'common',
  },
  {
    small: 'д',
    shift: 'Д',
    code: 'KeyL',
    size: 'common',
  },
  {
    small: 'ж',
    shift: 'Ж',
    code: 'Semicolon',
    size: 'common',
  },
  {
    small: 'э',
    shift: 'Э',
    code: 'Quote',
    size: 'common',
  },
  {
    small: 'Enter',
    shift: 'Enter',
    code: 'Enter',
    size: 'double',
  },
  {
    small: 'Shift',
    shift: 'Shift',
    code: 'ShiftLeft',
    size: 'double',
  },
  {
    small: 'я',
    shift: 'Я',
    code: 'KeyZ',
    size: 'common',
  },
  {
    small: 'ч',
    shift: 'Ч',
    code: 'KeyX',
    size: 'common',
  },
  {
    small: 'с',
    shift: 'С',
    code: 'KeyC',
    size: 'common',
  },
  {
    small: 'м',
    shift: 'М',
    code: 'KeyV',
    size: 'common',
  },
  {
    small: 'и',
    shift: 'И',
    code: 'KeyB',
    size: 'common',
  },
  {
    small: 'т',
    shift: 'Т',
    code: 'KeyN',
    size: 'common',
  },
  {
    small: 'ь',
    shift: 'Ь',
    code: 'KeyM',
    size: 'common',
  },
  {
    small: 'б',
    shift: 'Б',
    code: 'Comma',
    size: 'common',
  },
  {
    small: 'ю',
    shift: 'Ю',
    code: 'Period',
    size: 'common',
  },
  {
    small: '.',
    shift: ',',
    code: 'Slash',
    size: 'common',
  },
  {
    small: '',
    shift: '',
    code: 'ArrowUp',
    size: 'common',
  },
  {
    small: 'Shift',
    shift: 'Shift',
    code: 'ShiftRight',
    size: 'double',
  },
  {
    small: 'Ctrl',
    shift: 'Ctrl',
    code: 'ControlLeft',
    size: 'common',
  },
  {
    small: 'Win',
    shift: 'Win',
    code: 'MetaLeft',
    size: 'common',
  },
  {
    small: 'Alt',
    shift: 'Alt',
    code: 'AltLeft',
    size: 'common',
  },
  {
    small: 'Space',
    shift: 'Space',
    code: 'Space',
    size: 'space_button',
  },
  {
    small: 'Alt',
    shift: 'Alt',
    code: 'AltRight',
    size: 'common',
  },
  {
    small: '',
    shift: '',
    code: 'ArrowLeft',
    size: 'common',
  },
  {
    small: '',
    shift: '',
    code: 'ArrowDown',
    size: 'common',
  },
  {
    small: '',
    shift: '',
    code: 'ArrowRight',
    size: 'common',
  },
  {
    small: 'Ctrl',
    shift: 'Ctrl',
    code: 'ControlRight',
    size: 'common',
  },
];
